# Linear Algebra
:label:`sec_linear-algebra`

By now, we can load datasets into tensors
and manipulate these tensors 
with basic mathematical operations.
To start building sophisticated models,
we will also need a few tools from linear algebra. 
This section offers a gentle introduction 
to the most essential concepts,
starting from scalar arithmetic
and ramping up to matrix multiplication.


In [1]:
import torch

## Scalars


Most everyday mathematics
consists of manipulating 
numbers one at a time.
Formally, we call these values *scalars*.
For example, the temperature in Palo Alto 
is a balmy $72$ degrees Fahrenheit.
If you wanted to convert the temperature to Celsius
you would evaluate the expression 
$c = \frac{5}{9}(f - 32)$, setting $f$ to $72$.
In this equation, the values 
$5$, $9$, and $32$ are constant scalars.
The variables $c$ and $f$ 
in general represent unknown scalars.

We denote scalars
by ordinary lower-cased letters 
(e.g., $x$, $y$, and $z$)
and the space of all (continuous) 
*real-valued* scalars by $\mathbb{R}$.
For expedience, we will skip past
rigorous definitions of *spaces*:
just remember that the expression $x \in \mathbb{R}$
is a formal way to say that $x$ is a real-valued scalar.
The symbol $\in$ (pronounced "in")
denotes membership in a set.
For example, $x, y \in \{0, 1\}$
indicates that $x$ and $y$ are variables
that can only take values $0$ or $1$.

(**Scalars are implemented as tensors 
that contain only one element.**)
Below, we assign two scalars
and perform the familiar addition, multiplication,
division, and exponentiation operations.


In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## Vectors

For current purposes, [**you can think of a vector as a fixed-length array of scalars.**]
As with their code counterparts,
we call these scalars the *elements* of the vector
(synonyms include *entries* and *components*).
When vectors represent examples from real-world datasets,
their values hold some real-world significance.
For example, if we were training a model to predict
the risk of a loan defaulting,
we might associate each applicant with a vector
whose components correspond to quantities
like their income, length of employment, 
or number of previous defaults.
If we were studying the risk of heart attack,
each vector might represent a patient
and its components might correspond to
their most recent vital signs, cholesterol levels, 
minutes of exercise per day, etc.
We denote vectors by bold lowercase letters, 
(e.g., $\mathbf{x}$, $\mathbf{y}$, and $\mathbf{z}$).

Vectors are implemented as $1^{\textrm{st}}$-order tensors.
In general, such tensors can have arbitrary lengths,
subject to memory limitations. Caution: in Python, as in most programming languages, vector indices start at $0$, also known as *zero-based indexing*, whereas in linear algebra subscripts begin at $1$ (one-based indexing).


In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

We can refer to an element of a vector by using a subscript.
For example, $x_2$ denotes the second element of $\mathbf{x}$. 
Since $x_2$ is a scalar, we do not bold it.
By default, we visualize vectors 
by stacking their elements vertically.

$$\mathbf{x} =\begin{bmatrix}x_{1}  \\ \vdots  \\x_{n}\end{bmatrix},$$
:eqlabel:`eq_vec_def`

Here $x_1, \ldots, x_n$ are elements of the vector.
Later on, we will distinguish between such *column vectors*
and *row vectors* whose elements are stacked horizontally.
Recall that [**we access a tensor's elements via indexing.**]


In [4]:
x[1]

tensor(1)

To indicate that a vector contains $n$ elements,
we write $\mathbf{x} \in \mathbb{R}^n$.
Formally, we call $n$ the *dimensionality* of the vector.
[**In code, this corresponds to the tensor's length**],
accessible via Python's built-in `len` function.


In [5]:
len(x)

3

We can also access the length via the `shape` attribute.
The shape is a tuple that indicates a tensor's length along each axis.
(**Tensors with just one axis have shapes with just one element.**)


In [6]:
x.shape

torch.Size([3])

Oftentimes, the word "dimension" gets overloaded
to mean both the number of axes 
and the length along a particular axis.
To avoid this confusion, 
we use *order* to refer to the number of axes
and *dimensionality* exclusively to refer 
to the number of components.


## Matrices

Just as scalars are $0^{\textrm{th}}$-order tensors
and vectors are $1^{\textrm{st}}$-order tensors,
matrices are $2^{\textrm{nd}}$-order tensors.
We denote matrices by bold capital letters
(e.g., $\mathbf{X}$, $\mathbf{Y}$, and $\mathbf{Z}$),
and represent them in code by tensors with two axes.
The expression $\mathbf{A} \in \mathbb{R}^{m \times n}$
indicates that a matrix $\mathbf{A}$ 
contains $m \times n$ real-valued scalars,
arranged as $m$ rows and $n$ columns.
When $m = n$, we say that a matrix is *square*.
Visually, we can illustrate any matrix as a table.
To refer to an individual element,
we subscript both the row and column indices, e.g.,
$a_{ij}$ is the value that belongs to $\mathbf{A}$'s
$i^{\textrm{th}}$ row and $j^{\textrm{th}}$ column:

$$\mathbf{A}=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \\ \end{bmatrix}.$$
:eqlabel:`eq_matrix_def`


In code, we represent a matrix $\mathbf{A} \in \mathbb{R}^{m \times n}$
by a $2^{\textrm{nd}}$-order tensor with shape ($m$, $n$).
[**We can convert any appropriately sized $m \times n$ tensor 
into an $m \times n$ matrix**] 
by passing the desired shape to `reshape`:


In [7]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

Sometimes we want to flip the axes.
When we exchange a matrix's rows and columns,
the result is called its *transpose*.
Formally, we signify a matrix $\mathbf{A}$'s transpose 
by $\mathbf{A}^\top$ and if $\mathbf{B} = \mathbf{A}^\top$, 
then $b_{ij} = a_{ji}$ for all $i$ and $j$.
Thus, the transpose of an $m \times n$ matrix 
is an $n \times m$ matrix:

$$
\mathbf{A}^\top =
\begin{bmatrix}
    a_{11} & a_{21} & \dots  & a_{m1} \\
    a_{12} & a_{22} & \dots  & a_{m2} \\
    \vdots & \vdots & \ddots  & \vdots \\
    a_{1n} & a_{2n} & \dots  & a_{mn}
\end{bmatrix}.
$$

In code, we can access any (**matrix's transpose**) as follows:


In [8]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

[**Symmetric matrices are the subset of square matrices
that are equal to their own transposes:
$\mathbf{A} = \mathbf{A}^\top$.**]
The following matrix is symmetric:


In [19]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Matrices are useful for representing datasets. 
Typically, rows correspond to individual records
and columns correspond to distinct attributes.



## Tensors

While you can go far in your machine learning journey
with only scalars, vectors, and matrices,
eventually you may need to work with 
higher-order [**tensors**].
Tensors (**give us a generic way of describing 
extensions to $n^{\textrm{th}}$-order arrays.**)
We call software objects of the *tensor class* "tensors"
precisely because they too can have arbitrary numbers of axes.
While it may be confusing to use the word
*tensor* for both the mathematical object
and its realization in code,
our meaning should usually be clear from context.
We denote general tensors by capital letters 
with a special font face
(e.g., $\mathsf{X}$, $\mathsf{Y}$, and $\mathsf{Z}$)
and their indexing mechanism 
(e.g., $x_{ijk}$ and $[\mathsf{X}]_{1, 2i-1, 3}$) 
follows naturally from that of matrices.

Tensors will become more important 
when we start working with images.
Each image arrives as a $3^{\textrm{rd}}$-order tensor
with axes corresponding to the height, width, and *channel*.
At each spatial location, the intensities 
of each color (red, green, and blue)
are stacked along the channel. 
Furthermore, a collection of images is represented 
in code by a $4^{\textrm{th}}$-order tensor,
where distinct images are indexed
along the first axis.
Higher-order tensors are constructed, as were vectors and matrices,
by growing the number of shape components.


In [20]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## Basic Properties of Tensor Arithmetic

Scalars, vectors, matrices, 
and higher-order tensors
all have some handy properties. 
For example, elementwise operations
produce outputs that have the 
same shape as their operands.


In [21]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

The [**elementwise product of two matrices
is called their *Hadamard product***] (denoted $\odot$).
We can spell out the entries 
of the Hadamard product of two matrices 
$\mathbf{A}, \mathbf{B} \in \mathbb{R}^{m \times n}$:



$$
\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
    a_{11}  b_{11} & a_{12}  b_{12} & \dots  & a_{1n}  b_{1n} \\
    a_{21}  b_{21} & a_{22}  b_{22} & \dots  & a_{2n}  b_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1}  b_{m1} & a_{m2}  b_{m2} & \dots  & a_{mn}  b_{mn}
\end{bmatrix}.
$$


In [22]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

[**Adding or multiplying a scalar and a tensor**] produces a result
with the same shape as the original tensor.
Here, each element of the tensor is added to (or multiplied by) the scalar.


In [23]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## Reduction
:label:`subsec_lin-alg-reduction`

Often, we wish to calculate [**the sum of a tensor's elements.**]
To express the sum of the elements in a vector $\mathbf{x}$ of length $n$,
we write $\sum_{i=1}^n x_i$. There is a simple function for it:


In [24]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

To express [**sums over the elements of tensors of arbitrary shape**],
we simply sum over all its axes. 
For example, the sum of the elements 
of an $m \times n$ matrix $\mathbf{A}$ 
could be written $\sum_{i=1}^{m} \sum_{j=1}^{n} a_{ij}$.


In [25]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

By default, invoking the sum function
*reduces* a tensor along all of its axes,
eventually producing a scalar.
Our libraries also allow us to [**specify the axes 
along which the tensor should be reduced.**]
To sum over all elements along the rows (axis 0),
we specify `axis=0` in `sum`.
Since the input matrix reduces along axis 0
to generate the output vector,
this axis is missing from the shape of the output.


In [26]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

Specifying `axis=1` will reduce the column dimension (axis 1) by summing up elements of all the columns.


In [27]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

Reducing a matrix along both rows and columns via summation
is equivalent to summing up all the elements of the matrix.


In [28]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

[**A related quantity is the *mean*, also called the *average*.**]
We calculate the mean by dividing the sum 
by the total number of elements.
Because computing the mean is so common,
it gets a dedicated library function 
that works analogously to `sum`.


In [29]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

Likewise, the function for calculating the mean 
can also reduce a tensor along specific axes.


In [30]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

## Non-Reduction Sum
:label:`subsec_lin-alg-non-reduction`

Sometimes it can be useful to [**keep the number of axes unchanged**]
when invoking the function for calculating the sum or mean. 
This matters when we want to use the broadcast mechanism.


In [31]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

For instance, since `sum_A` keeps its two axes after summing each row,
we can (**divide `A` by `sum_A` with broadcasting**) 
to create a matrix where each row sums up to $1$.


In [32]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

If we want to calculate [**the cumulative sum of elements of `A` along some axis**],
say `axis=0` (row by row), we can call the `cumsum` function.
By design, this function does not reduce the input tensor along any axis.


In [33]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

## Dot Products

So far, we have only performed elementwise operations, sums, and averages. 
And if this was all we could do, linear algebra 
would not deserve its own section.
Fortunately, this is where things get more interesting.
One of the most fundamental operations is the dot product.
Given two vectors $\mathbf{x}, \mathbf{y} \in \mathbb{R}^d$,
their *dot product* $\mathbf{x}^\top \mathbf{y}$ (also known as *inner product*, $\langle \mathbf{x}, \mathbf{y}  \rangle$) 
is a sum over the products of the elements at the same position: 
$\mathbf{x}^\top \mathbf{y} = \sum_{i=1}^{d} x_i y_i$.

[~~The *dot product* of two vectors is a sum over the products of the elements at the same position~~]


In [34]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

Equivalently, (**we can calculate the dot product of two vectors 
by performing an elementwise multiplication followed by a sum:**)


In [35]:
torch.sum(x * y)

tensor(3.)

Dot products are useful in a wide range of contexts.
For example, given some set of values,
denoted by a vector $\mathbf{x}  \in \mathbb{R}^n$,
and a set of weights, denoted by $\mathbf{w} \in \mathbb{R}^n$,
the weighted sum of the values in $\mathbf{x}$
according to the weights $\mathbf{w}$
could be expressed as the dot product $\mathbf{x}^\top \mathbf{w}$.
When the weights are nonnegative
and sum to $1$, i.e., $\left(\sum_{i=1}^{n} {w_i} = 1\right)$,
the dot product expresses a *weighted average*.
After normalizing two vectors to have unit length,
the dot products express the cosine of the angle between them.
Later in this section, we will formally introduce this notion of *length*.


## Matrix--Vector Products

Now that we know how to calculate dot products,
we can begin to understand the *product*
between an $m \times n$ matrix $\mathbf{A}$ 
and an $n$-dimensional vector $\mathbf{x}$.
To start off, we visualize our matrix
in terms of its row vectors

$$\mathbf{A}=
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix},$$

where each $\mathbf{a}^\top_{i} \in \mathbb{R}^n$
is a row vector representing the $i^\textrm{th}$ row 
of the matrix $\mathbf{A}$.

[**The matrix--vector product $\mathbf{A}\mathbf{x}$
is simply a column vector of length $m$,
whose $i^\textrm{th}$ element is the dot product 
$\mathbf{a}^\top_i \mathbf{x}$:**]

$$
\mathbf{A}\mathbf{x}
= \begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_m \\
\end{bmatrix}\mathbf{x}
= \begin{bmatrix}
 \mathbf{a}^\top_{1} \mathbf{x}  \\
 \mathbf{a}^\top_{2} \mathbf{x} \\
\vdots\\
 \mathbf{a}^\top_{m} \mathbf{x}\\
\end{bmatrix}.
$$

We can think of multiplication with a matrix
$\mathbf{A}\in \mathbb{R}^{m \times n}$
as a transformation that projects vectors
from $\mathbb{R}^{n}$ to $\mathbb{R}^{m}$.
These transformations are remarkably useful.
For example, we can represent rotations
as multiplications by certain square matrices.
Matrix--vector products also describe 
the key calculation involved in computing
the outputs of each layer in a neural network
given the outputs from the previous layer.


To express a matrix--vector product in code,
we use the `mv` function. 
Note that the column dimension of `A` 
(its length along axis 1)
must be the same as the dimension of `x` (its length). 
Python has a convenience operator `@` 
that can execute both matrix--vector
and matrix--matrix products
(depending on its arguments). 
Thus we can write `A@x`.


In [36]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

## Matrix--Matrix Multiplication

Once you have gotten the hang of dot products and matrix--vector products,
then *matrix--matrix multiplication* should be straightforward.

Say that we have two matrices 
$\mathbf{A} \in \mathbb{R}^{n \times k}$ 
and $\mathbf{B} \in \mathbb{R}^{k \times m}$:

$$\mathbf{A}=\begin{bmatrix}
 a_{11} & a_{12} & \cdots & a_{1k} \\
 a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nk} \\
\end{bmatrix},\quad
\mathbf{B}=\begin{bmatrix}
 b_{11} & b_{12} & \cdots & b_{1m} \\
 b_{21} & b_{22} & \cdots & b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 b_{k1} & b_{k2} & \cdots & b_{km} \\
\end{bmatrix}.$$


Let $\mathbf{a}^\top_{i} \in \mathbb{R}^k$ denote 
the row vector representing the $i^\textrm{th}$ row 
of the matrix $\mathbf{A}$
and let $\mathbf{b}_{j} \in \mathbb{R}^k$ denote 
the column vector from the $j^\textrm{th}$ column 
of the matrix $\mathbf{B}$:

$$\mathbf{A}=
\begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_n \\
\end{bmatrix},
\quad \mathbf{B}=\begin{bmatrix}
 \mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m} \\
\end{bmatrix}.
$$


To form the matrix product $\mathbf{C} \in \mathbb{R}^{n \times m}$,
we simply compute each element $c_{ij}$
as the dot product between 
the $i^{\textrm{th}}$ row of $\mathbf{A}$
and the $j^{\textrm{th}}$ column of $\mathbf{B}$,
i.e., $\mathbf{a}^\top_i \mathbf{b}_j$:

$$\mathbf{C} = \mathbf{AB} = \begin{bmatrix}
\mathbf{a}^\top_{1} \\
\mathbf{a}^\top_{2} \\
\vdots \\
\mathbf{a}^\top_n \\
\end{bmatrix}
\begin{bmatrix}
 \mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m} \\
\end{bmatrix}
= \begin{bmatrix}
\mathbf{a}^\top_{1} \mathbf{b}_1 & \mathbf{a}^\top_{1}\mathbf{b}_2& \cdots & \mathbf{a}^\top_{1} \mathbf{b}_m \\
 \mathbf{a}^\top_{2}\mathbf{b}_1 & \mathbf{a}^\top_{2} \mathbf{b}_2 & \cdots & \mathbf{a}^\top_{2} \mathbf{b}_m \\
 \vdots & \vdots & \ddots &\vdots\\
\mathbf{a}^\top_{n} \mathbf{b}_1 & \mathbf{a}^\top_{n}\mathbf{b}_2& \cdots& \mathbf{a}^\top_{n} \mathbf{b}_m
\end{bmatrix}.
$$

[**We can think of the matrix--matrix multiplication $\mathbf{AB}$
as performing $m$ matrix--vector products 
or $m \times n$ dot products 
and stitching the results together 
to form an $n \times m$ matrix.**]
In the following snippet, 
we perform matrix multiplication on `A` and `B`.
Here, `A` is a matrix with two rows and three columns,
and `B` is a matrix with three rows and four columns.
After multiplication, we obtain a matrix with two rows and four columns.


In [37]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

The term *matrix--matrix multiplication* is 
often simplified to *matrix multiplication*,
and should not be confused with the Hadamard product.


## Norms
:label:`subsec_lin-algebra-norms`

Some of the most useful operators in linear algebra are *norms*.
Informally, the norm of a vector tells us how *big* it is. 
For instance, the $\ell_2$ norm measures
the (Euclidean) length of a vector.
Here, we are employing a notion of *size* that concerns the magnitude of a vector's components
(not its dimensionality). 

A norm is a function $\| \cdot \|$ that maps a vector
to a scalar and satisfies the following three properties:

1. Given any vector $\mathbf{x}$, if we scale (all elements of) the vector 
   by a scalar $\alpha \in \mathbb{R}$, its norm scales accordingly:
   $$\|\alpha \mathbf{x}\| = |\alpha| \|\mathbf{x}\|.$$
2. For any vectors $\mathbf{x}$ and $\mathbf{y}$:
   norms satisfy the triangle inequality:
   $$\|\mathbf{x} + \mathbf{y}\| \leq \|\mathbf{x}\| + \|\mathbf{y}\|.$$
3. The norm of a vector is nonnegative and it only vanishes if the vector is zero:
   $$\|\mathbf{x}\| > 0 \textrm{ for all } \mathbf{x} \neq 0.$$

Many functions are valid norms and different norms 
encode different notions of size. 
The Euclidean norm that we all learned in elementary school geometry
when calculating the hypotenuse of a right triangle
is the square root of the sum of squares of a vector's elements.
Formally, this is called [**the $\ell_2$ *norm***] and expressed as

(**$$\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2}.$$**)

The method `norm` calculates the $\ell_2$ norm.


In [38]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

[**The $\ell_1$ norm**] is also common 
and the associated measure is called the Manhattan distance. 
By definition, the $\ell_1$ norm sums 
the absolute values of a vector's elements:

(**$$\|\mathbf{x}\|_1 = \sum_{i=1}^n \left|x_i \right|.$$**)

Compared to the $\ell_2$ norm, it is less sensitive to outliers.
To compute the $\ell_1$ norm, 
we compose the absolute value
with the sum operation.


In [39]:
torch.abs(u).sum()

tensor(7.)

Both the $\ell_2$ and $\ell_1$ norms are special cases
of the more general $\ell_p$ *norms*:

$$\|\mathbf{x}\|_p = \left(\sum_{i=1}^n \left|x_i \right|^p \right)^{1/p}.$$

In the case of matrices, matters are more complicated. 
After all, matrices can be viewed both as collections of individual entries 
*and* as objects that operate on vectors and transform them into other vectors. 
For instance, we can ask by how much longer 
the matrix--vector product $\mathbf{X} \mathbf{v}$ 
could be relative to $\mathbf{v}$. 
This line of thought leads to what is called the *spectral* norm. 
For now, we introduce [**the *Frobenius norm*, 
which is much easier to compute**] and defined as
the square root of the sum of the squares 
of a matrix's elements:

[**$$\|\mathbf{X}\|_\textrm{F} = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}.$$**]

The Frobenius norm behaves as if it were 
an $\ell_2$ norm of a matrix-shaped vector.
Invoking the following function will calculate 
the Frobenius norm of a matrix.


In [40]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

## Latex101 remedy 
$\mathbf{A}^\top$ <br>
$x,\; \lambda,\; \alpha$ <br>
$\mathbf{x} \in \mathbb{R}^n$ <br>
$\mathbb{R}, \mathbb{N}, \mathbb{Z}$ <br>
$$
\nabla_\theta L = \frac{\partial L}{\partial \theta} 
$$
$\mathbb{R}^{2^{10} \times 2^{16}}$ <br>
$\text{axis}=1$ <br>
$x \in \mathbb{R}^n$ <br>
$\mathbf{A} \mathbf{B}$ <br>
$\mathbf{x} \cdot \mathbf{y}$ <br>


1. In Jupyter, LaTeX = anything inside dollar signs; **vectors are \mathbf**, **shapes live in \mathbb{R}^{m \times n}**, **gradients use \nabla**, and **superscripts/subscripts are ^ and _**.
1. \ starts a command 
1. {} group things (not visible)
1. ^ and _ affect ONE token → use {} for more
1. Commands like \frac, \mathbf, \mathbb need {}
1. ( ) are math, { } are control
1. Spaces don’t matter in math
1. If it looks like a word → it needs \



While we do not want to get too far ahead of ourselves,
we already can plant some intuition about why these concepts are useful.
In deep learning, we are often trying to solve optimization problems:
*maximize* the probability assigned to observed data;
*maximize* the revenue associated with a recommender model; 
*minimize* the distance between predictions
and the ground truth observations; 
*minimize* the distance between representations 
of photos of the same person 
while *maximizing* the distance between representations 
of photos of different people. 
These distances, which constitute 
the objectives of deep learning algorithms, 
are often expressed as norms. 


## Discussion

In this section, we have reviewed all the linear algebra
that you will need to understand
a significant chunk of modern deep learning.
There is a lot more to linear algebra, though,
and much of it is useful for machine learning.
For example, matrices can be decomposed into factors,
and these decompositions can reveal
low-dimensional structure in real-world datasets.
There are entire subfields of machine learning
that focus on using matrix decompositions
and their generalizations to high-order tensors
to discover structure in datasets 
and solve prediction problems.
But this book focuses on deep learning.
And we believe you will be more inclined 
to learn more mathematics
once you have gotten your hands dirty
applying machine learning to real datasets.
So while we reserve the right 
to introduce more mathematics later on,
we wrap up this section here.

If you are eager to learn more linear algebra,
there are many excellent books and online resources.
For a more advanced crash course, consider checking out
:citet:`Strang.1993`, :citet:`Kolter.2008`, and :citet:`Petersen.Pedersen.ea.2008`.

To recap:

* Scalars, vectors, matrices, and tensors are 
  the basic mathematical objects used in linear algebra 
  and have zero, one, two, and an arbitrary number of axes, respectively.
* Tensors can be sliced or reduced along specified axes 
  via indexing, or operations such as `sum` and `mean`, respectively.
* Elementwise products are called Hadamard products. 
  By contrast, dot products, matrix--vector products, and matrix--matrix products 
  are not elementwise operations and in general return objects 
  having shapes that are different from the the operands. 
* Compared to Hadamard products, matrix--matrix products 
  take considerably longer to compute (cubic rather than quadratic time).
* Norms capture various notions of the magnitude of a vector (or matrix), 
  and are commonly applied to the difference of two vectors 
  to measure their distance apart.
* Common vector norms include the $\ell_1$ and $\ell_2$ norms, 
   and common matrix norms include the *spectral* and *Frobenius* norms.


## Exercises

1. Prove that the transpose of the transpose of a matrix is the matrix itself: $(\mathbf{A}^\top)^\top = \mathbf{A}$.
1. Given two matrices $\mathbf{A}$ and $\mathbf{B}$, show that sum and transposition commute: $\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$.
1. Given any square matrix $\mathbf{A}$, is $\mathbf{A} + \mathbf{A}^\top$ always symmetric? Can you prove the result by using only the results of the previous two exercises?
1. We defined the tensor `X` of shape (2, 3, 4) in this section. What is the output of `len(X)`? Write your answer without implementing any code, then check your answer using code. 
1. For a tensor `X` of arbitrary shape, does `len(X)` always correspond to the length of a certain axis of `X`? What is that axis?
1. Run `A / A.sum(axis=1)` and see what happens. Can you analyze the results?
1. <span style="color:orange">When traveling between two points in downtown Manhattan, what is the distance that you need to cover in terms of the coordinates, i.e., in terms of avenues and streets? Can you travel diagonally? </span><br>
1. Consider a tensor of shape (2, 3, 4). What are the shapes of the summation outputs along axes 0, 1, and 2?
1. Feed a tensor with three or more axes to the `linalg.norm` function and observe its output. What does this function compute for tensors of arbitrary shape?
1.  <span style="color:orange"> Consider three large matrices, say $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{14}}$, initialized with Gaussian random variables. You want to compute the product $\mathbf{A} \mathbf{B} \mathbf{C}$. Is there any difference in memory footprint and speed, depending on whether you compute $(\mathbf{A} \mathbf{B}) \mathbf{C}$ or $\mathbf{A} (\mathbf{B} \mathbf{C})$. Why? <span>
1. Consider three large matrices, say $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{16}}$. Is there any difference in speed depending on whether you compute $\mathbf{A} \mathbf{B}$ or $\mathbf{A} \mathbf{C}^\top$? Why? What changes if you initialize $\mathbf{C} = \mathbf{B}^\top$ without cloning memory? Why? 
1. Consider three matrices, say $\mathbf{A}, \mathbf{B}, \mathbf{C} \in \mathbb{R}^{100 \times 200}$. Construct a tensor with three axes by stacking $[\mathbf{A}, \mathbf{B}, \mathbf{C}]$. What is the dimensionality? Slice out the second coordinate of the third axis to recover $\mathbf{B}$. Check that your answer is correct.


##  Exercise Answers (before correction) 

1. use element wise notion of A to denote $A^\top , (A^\top)^\top$ <br>
1. same process as Q1 <br>
1. $A+A^\top = (A^\top)^T + A^\top = (A^\top+ A)^\top = (A + A^\top)^\top$ <br>
1. the len(x) would return 2 (dimension of axis=0) <br>
1. answered in Q4 <br>
1. it won't work as python aligns 1D tensor of length 2 from the right most dimension of A which is 3 intead of 2 <br>
1. you would need to travel the distance which equals to the differences of the the vertical and horizontal axises <br> or in the units of avenues and streets, you cannot travel diagonally directly, you have to move each step either horizontally or vertically
1. (3,4) (2,4) (2,3)
1. it would treat all elements as elements in a single vector and compute the ord=2 norm
2. Yes, **A**(**BC)** would work faster  than (**AB**)**C**, as if A is large AB would take longer time compared to doing (BC) first
3. Yes, as the numbers inside **B** or **C** is different. But after the initiazation it would be the same.
4. [100,200,3] (if stack on axis=2) if use the stack by default, it is [3,100,200]
   

In [41]:
#Q4.
X = torch.arange(24, dtype=torch.float32).reshape(2,3,4)
print(X)
print(len(X))

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])
2


In [44]:
print(A)
print(A.shape)
print(A.sum(axis=1).shape)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
torch.Size([2, 3])
torch.Size([2])


In [47]:
#Q6
# print(A/A.sum(axis=1,keepdims=False)) 
print(A/A.sum(axis=1, keepdims=True))

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])


<u>the  "print(A/A.sum(axis=1,keepdims=False)) " would return error as python aligns the 1D tensor from the right most dimension of A which is axis=1 andhas dimension 3 </u>

In [48]:
# Q8
print((X.sum(axis=1)).shape)
print((X.sum(axis=1,keepdims=True)).shape)

torch.Size([2, 4])
torch.Size([2, 1, 4])


<span style="color:red">#Q7(?) </span><br>

In [67]:
A=torch.ones(2,5)
B=2*torch.ones(2,5)
C=3*torch.ones(2,5)
D=torch.stack([A, B, C], dim=-1)

In [68]:
print(D[:,:,1])

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])


# D2L Linear Algebra — Exercises 1–4 (Corrected, Rigorous)

---

## 1) Prove $({\bf A}^\top)^\top = {\bf A}$

Let ${\bf A}\in\mathbb{R}^{m\times n}$. By the definition of transpose, for any valid indices $i,j$:

- $({\bf A}^\top)_{ij} = A_{ji}$

Transpose again:

- $(({\bf A}^\top)^\top)_{ij} = ({\bf A}^\top)_{ji} = A_{ij}$

Since every entry matches, we conclude:
- $({\bf A}^\top)^\top = {\bf A}$.

**Common mistakes / reminders**
- Saying “element-wise” without writing the index equation $((\cdot)_{ij})$ is not a proof.
- Confusing ${\bf A}^\top$ (transpose) with ${\bf A}^{-1}$ (inverse). Totally different.

---

## 2) Show ${\bf A}^\top + {\bf B}^\top = ({\bf A}+{\bf B})^\top$

Assume ${\bf A},{\bf B}$ have the same shape $m\times n$. For any $i,j$:

- $(({\bf A}+{\bf B})^\top)_{ij} = ({\bf A}+{\bf B})_{ji} = A_{ji}+B_{ji}$  
- $( {\bf A}^\top + {\bf B}^\top )_{ij} = ({\bf A}^\top)_{ij} + ({\bf B}^\top)_{ij} = A_{ji}+B_{ji}$

Thus, the two matrices have identical entries for all $i,j$, so:
- $({\bf A}+{\bf B})^\top = {\bf A}^\top + {\bf B}^\top$.

**Common mistakes / reminders**
- Forgetting the condition “same shape” for ${\bf A}+{\bf B}$.
- Writing “same as Q1” without actually showing the equality.

---

## 3) Is ${\bf A}+{\bf A}^\top$ always symmetric?

Yes (for any square ${\bf A}\in\mathbb{R}^{n\times n}$).

A matrix ${\bf S}$ is symmetric iff ${\bf S}^\top={\bf S}$. Let ${\bf S}={\bf A}+{\bf A}^\top$. Then:

- ${\bf S}^\top = ({\bf A}+{\bf A}^\top)^\top$  
- Using Q2: $({\bf A}+{\bf A}^\top)^\top = {\bf A}^\top + ({\bf A}^\top)^\top$  
- Using Q1: $({\bf A}^\top)^\top = {\bf A}$

So:
- ${\bf S}^\top = {\bf A}^\top + {\bf A} = {\bf A}+{\bf A}^\top = {\bf S}$

Therefore ${\bf A}+{\bf A}^\top$ is symmetric.

**Common mistakes / reminders**
- This requires ${\bf A}$ to be square so that ${\bf A}$ and ${\bf A}^\top$ have the same shape and can be added.
- “Symmetric” means equal to its transpose, not “looks mirrored” in some vague sense.

---

## 4) If $X$ has shape $(2,3,4)$, what is `len(X)`?

`len(X)` is the size of the **first axis** (axis 0).  
So for shape $(2,3,4)$:

- $\texttt{len}(X)=2$

**Common mistakes / reminders**
- `len(X)` is **not** the total number of elements (that would be `X.numel()` in PyTorch / `X.size` in NumPy).
- `len(X)` is **not** the number of axes (that would be `X.ndim` / `X.dim()`).




## 5) For arbitrary shape, does `len(X)` correspond to which axis?

Yes. For any tensor/array `X` with shape $(d_0, d_1, \dots, d_{k-1})$:

- $\texttt{len}(X)=d_0$

So `len(X)` always returns the length of **axis 0** (the first axis).

**Common mistakes / reminders**
- People often think broadcasting/shape logic is “left-aligned”; `len` is always about the **first** axis, not the last.
- If `X` is a scalar (0-D tensor), `len(X)` is not defined (it errors).

---

## 6) Run `A / A.sum(axis=1)` — what happens and why?

Assume (as in D2L) that `A` is a 2D tensor, e.g. shape $(2,3)$.

1) Shapes:
- $A\in\mathbb{R}^{2\times 3}$
- `A.sum(axis=1)` sums across columns, so its shape is $(2,)$  
  (one sum per row)

2) Division tries elementwise broadcasting:
- We attempt $A \oslash s$ where $s = A.sum(axis=1)$ has shape $(2,)$.

Broadcasting aligns shapes **from the right**:
- $A$ has shape $(2,3)$
- $s$ has shape $(2)$, which lines up with the **last** dimension of $A$ (which is 3)

Mismatch:
- last dim: $3$ vs $2$  → cannot broadcast → runtime error.

3) Correct fix (make the divisor shape $(2,1)$ so it broadcasts across columns):
- Use `keepdims=True` so the summed axis stays as length 1:
  - `A.sum(axis=1, keepdims=True)` has shape $(2,1)$
- Then $(2,3)$ divided by $(2,1)$ broadcasts to $(2,3)$.

Mathematically, this computes **row-normalization**:
- Let $r_i=\sum_{j=1}^{3}A_{ij}$
- Output entries: $\tilde A_{ij} = A_{ij}/r_i$

**Common mistakes / reminders**
- Broadcasting is **right-aligned**, not left-aligned.
- In PyTorch, use `dim` not `axis` (NumPy uses `axis`). D2L sometimes abstracts this via its backend wrapper.
- If any row sum is 0, you’ll get division-by-zero issues (inf/nan).

---

## 7) Manhattan travel distance (avenues/streets): can you go diagonally?

In a grid city like Manhattan, you typically move only along:
- avenues (say $x$ direction)
- streets (say $y$ direction)

So from point $(x_1,y_1)$ to $(x_2,y_2)$, the distance you must cover is:

- $d_{\text{Manhattan}} = |x_1-x_2| + |y_1-y_2|$

This is the **Manhattan distance**, also called the **$L_1$ norm** distance:
- $d = \| (x_1-x_2,\, y_1-y_2)\|_1$

Diagonal shortcuts (straight-line through buildings) are not allowed in the basic grid model, so you cannot “cut across” to reduce $|x_1-x_2| + |y_1-y_2|$.

**Common mistakes / reminders**
- Do not confuse with Euclidean distance (straight line):
  - $d_{\text{Euclid}}=\sqrt{(x_1-x_2)^2+(y_1-y_2)^2}$
- Manhattan distance is about constrained movement, not geometry alone.

---

## 8) For shape $(2,3,4)$, what are the shapes of `sum` along axes 0, 1, 2?

Let $X$ have shape $(2,3,4)$.

- Sum over axis 0 removes the first dimension:
  - `X.sum(axis=0)` has shape $(3,4)$
- Sum over axis 1 removes the second dimension:
  - `X.sum(axis=1)` has shape $(2,4)$
- Sum over axis 2 removes the third dimension:
  - `X.sum(axis=2)` has shape $(2,3)$

Rule: summing over axis $k$ removes dimension $k$ (unless you keep it with `keepdims=True`).

**Common mistakes / reminders**
- Axis counting starts at 0.
- `keepdims=True` keeps the axis as size 1 (useful for broadcasting).



## 9) What does `linalg.norm` compute for tensors with 3+ axes?

Default behavior (typical in NumPy / PyTorch): if you call `linalg.norm(X)` **without specifying `axis`**, it treats all entries of $X$ as one long vector and computes the Euclidean norm:

- $\|X\|_2 = \sqrt{\sum_{i} X_i^2}$  
  (where $i$ ranges over *all* elements of the tensor)

So it is equivalent to flattening:
- $\|X\|_2 = \|\text{vec}(X)\|_2$

If you specify `axis`, it computes norms along that axis (or axes), producing a tensor of norms.

**Common mistakes / reminders**
- “It always flattens” is only true for the default call; `axis` changes the meaning.
- Different `ord` values give different norms (e.g., $L_1$, Frobenius, etc.), depending on library and arguments.

---

## 10) Compute ${\bf A}{\bf B}{\bf C}$: is $(AB)C$ vs $A(BC)$ different?

Given:
- ${\bf A}\in\mathbb{R}^{2^{10}\times 2^{16}}$
- ${\bf B}\in\mathbb{R}^{2^{16}\times 2^{5}}$
- ${\bf C}\in\mathbb{R}^{2^{5}\times 2^{14}}$

### Intermediate sizes (this is the key)
1) $(AB)$ has shape:
- $(2^{10}\times 2^{5})$
because $(2^{10}\times 2^{16})(2^{16}\times 2^{5})\to (2^{10}\times 2^{5})$

Then $(AB)C$ multiplies:
- $(2^{10}\times 2^{5})(2^{5}\times 2^{14})\to (2^{10}\times 2^{14})$

2) $(BC)$ has shape:
- $(2^{16}\times 2^{14})$
because $(2^{16}\times 2^{5})(2^{5}\times 2^{14})\to (2^{16}\times 2^{14})$

Then $A(BC)$ multiplies:
- $(2^{10}\times 2^{16})(2^{16}\times 2^{14})\to (2^{10}\times 2^{14})$

### Memory footprint
- $(AB)$ intermediate: $2^{10}\cdot 2^{5} = 2^{15}$ entries (small)
- $(BC)$ intermediate: $2^{16}\cdot 2^{14} = 2^{30}$ entries (massive)

So **$(AB)C$ uses dramatically less memory**.

### Speed (FLOPs)
Matrix multiply cost (roughly): $(m\times k)(k\times n)$ costs $O(mkn)$ multiplications.

- Cost of $AB$: $2^{10}\cdot 2^{16}\cdot 2^{5} = 2^{31}$
- Cost of $(AB)C$: $2^{10}\cdot 2^{5}\cdot 2^{14} = 2^{29}$
- Total for $(AB)C$: $2^{31}+2^{29}$

- Cost of $BC$: $2^{16}\cdot 2^{5}\cdot 2^{14} = 2^{35}$
- Cost of $A(BC)$: $2^{10}\cdot 2^{16}\cdot 2^{14} = 2^{40}$
- Total for $A(BC)$: $2^{35}+2^{40}$ (much larger)

**Conclusion:** $(AB)C$ is both **faster** and **far smaller** in memory than $A(BC)$ here.

**Common mistakes / reminders**
- Your original intuition “do BC first” is wrong for these specific dimensions because $(BC)$ explodes in size.
- Always compare *intermediate shapes* and *FLOPs*.

---

## 11) Speed: compute $AB$ or $AC^\top$? What if $C=B^\top$ without cloning?

Given:
- ${\bf A}\in\mathbb{R}^{2^{10}\times 2^{16}}$
- ${\bf B}\in\mathbb{R}^{2^{16}\times 2^{5}}$
- ${\bf C}\in\mathbb{R}^{2^{5}\times 2^{16}}$

Both products $AB$ and $A C^\top$ have the same output shape:
- $AB$: $(2^{10}\times 2^{16})(2^{16}\times 2^5)\to (2^{10}\times 2^5)$
- $AC^\top$: $(2^{10}\times 2^{16})(2^{16}\times 2^5)\to (2^{10}\times 2^5)$ since $C^\top\in\mathbb{R}^{2^{16}\times 2^5}$

### FLOPs
They are the same order:
- both cost about $2^{10}\cdot 2^{16}\cdot 2^5 = 2^{31}$

### Why speed can still differ in practice
Because of **memory layout / contiguity**:
- A transposed view like $C^\top$ may be **non-contiguous** (different strides).
- Many fast GEMM kernels (BLAS) run best when inputs are contiguous or in preferred layouts.
- If $C^\top$ is non-contiguous, the library may:
  - create a contiguous copy internally, or
  - use a slower kernel.

### If you set $C=B^\top$ *without cloning*
Then $C$ shares memory with $B$ (a view), so $C^\top$ is (often) essentially $B$ again, but the **stride pattern** can still matter. Also:
- Some operations will trigger implicit copies to get contiguous blocks.
- Sharing memory can be good for saving RAM, but can cause surprising performance differences.

**Conclusion:** numerical values do not determine speed; **layout and contiguity** do.

**Common mistakes / reminders**
- “B and C have different numbers so speed differs” — false.
- The main issue is *strides/cache/BLAS kernels*, not math.

---

## 12) Stack ${\bf A},{\bf B},{\bf C}\in\mathbb{R}^{100\times 200}$ into a 3-axis tensor; recover ${\bf B}$

If you use a standard stack (e.g., `stack([A,B,C])`), it creates a new leading axis:

- Shape becomes $(3,100,200)$

Index meaning:
- axis 0 selects which matrix: 0→$A$, 1→$B$, 2→$C$

To recover ${\bf B}$:
- slice index 1 on axis 0:
  - $X[1,:,:]$ has shape $(100,200)$ and equals ${\bf B}$.

If instead you stack along a new last axis (conceptually “put them side-by-side in a third axis”), you can get:
- shape $(100,200,3)$
and then ${\bf B}$ is:
- $X[:,:,1]$

**Common mistakes / reminders**
- Default stack usually makes shape $(3,100,200)$, not $(100,200,3)$.
- Mixing up `stack` vs `concatenate`: concatenate does not create a new axis; stack does.


[Discussions](https://discuss.d2l.ai/t/31)
